-- =============================================================================
-- MODULE: Encoding & Serialization
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('json-marshal-user','Encoding & Serialization','function','go','JSON Marshal User','Marshal a User struct (Name, Email, Age) into a JSON string. Export fields as lowercase JSON keys.','MarshalUser','string',ARRAY['string','string','int']::text[],ARRAY['Define User struct with json tags: json:"name", json:"email", json:"age".','Use json.Marshal to convert to JSON bytes.','Cast the bytes to string.'],1,60,ARRAY['json','serialization','structs','basic'],true,'MANUAL:json-marshal-user',$$Marshal a User struct to JSON.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["Alice","alice@example.com",30]'::jsonb,'"{\"name\":\"Alice\",\"email\":\"alice@example.com\",\"age\":30}"',false,1),('["Bob","bob@test.com",25]'::jsonb,'"{\"name\":\"Bob\",\"email\":\"bob@test.com\",\"age\":25}"',false,2),('["",null,0]'::jsonb,'"{\"name\":\"\",\"email\":null,\"age\":0}"',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('json-unmarshal','Encoding & Serialization','function','go','JSON Unmarshal','Given a JSON string representing a Product (name, price, inStock), return a map of its fields.','UnmarshalProduct','map[string]interface{}',ARRAY['string']::text[],ARRAY['Define Product struct and use json.Unmarshal.','Return map with "name", "price", "inStock" keys.','Handle the case of invalid JSON gracefully (return nil map).'],2,80,ARRAY['json','deserialization','structs','medium'],true,'MANUAL:json-unmarshal',$$Unmarshal JSON to a Product struct.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["{\"name\":\"Widget\",\"price\":9.99,\"inStock\":true}"]'::jsonb,'{"name":"Widget","price":9.99,"inStock":true}',false,1),('["{\"name\":\"Gadget\",\"price\":24.95,\"inStock\":false}"]'::jsonb,'{"name":"Gadget","price":24.95,"inStock":false}',false,2),('["invalid"]'::jsonb,'{}',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('base64-encode','Encoding & Serialization','function','go','Base64 Encode','Encode a given string to base64 and return the encoded string.','Base64Encode','string',ARRAY['string']::text[],ARRAY['Use encoding/base64.StdEncoding.EncodeToString.','Convert the string to []byte first.','Return the encoded string.'],1,40,ARRAY['encoding','base64','basic'],true,'MANUAL:base64-encode',$$Encode a string to base64.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["Hello, World!"]'::jsonb,'"SGVsbG8sIFdvcmxkIQ=="',false,1),('["Go"]'::jsonb,'"R28="',false,2),('[""]'::jsonb,'""',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('hex-encode','Encoding & Serialization','function','go','Hex Encode','Encode a byte slice to a hexadecimal string and return it.','HexEncode','string',ARRAY['[]int']::text[],ARRAY['Convert []int to []byte first (each int 0-255).','Use encoding/hex.EncodeToString.','Return the hex string.'],1,40,ARRAY['encoding','hex','basic'],true,'MANUAL:hex-encode',$$Encode a byte slice to hex string.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[72,101,108,108,111]]'::jsonb,'"48656c6c6f"',false,1),('[[0,255,128,64]]'::jsonb,'"00ff8040"',false,2),('[[]]'::jsonb,'""',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('csv-encode','Encoding & Serialization','function','go','CSV Row Encode','Encode a slice of string fields into a CSV row. Quote fields containing commas or quotes.','CSVEncodeRow','string',ARRAY['[]string']::text[],ARRAY['For each field, if it contains a comma or quote, wrap in double quotes.','Escape existing quotes in a field by doubling them.','Join fields with commas.'],2,80,ARRAY['encoding','csv','strings','medium'],true,'MANUAL:csv-encode',$$Encode a row of fields as a CSV line.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[["a","b","c"]]'::jsonb,'"a,b,c"',false,1),('[["hello, world","foo","bar"]]'::jsonb,'"\"hello, world\",foo,bar"',false,2),('[["\"quote\""]]'::jsonb,'"\"\"\"quote\"\"\""',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('gob-encode','Encoding & Serialization','function','go','Gob Encode/Decode','Demonstrate Go''s binary encoding (gob). Encode a Point{X,Y int} to bytes and decode it back. Return the decoded point slice.','GobPoint','[]int',ARRAY['[]int']::text[],ARRAY['Input is a slice [x, y]. Create a Point struct.','Use gob.NewEncoder with a bytes.Buffer.','Encode then decode; return []int{decoded.X, decoded.Y}.'],3,110,ARRAY['encoding','gob','serialization','medium'],true,'MANUAL:gob-encode',$$Gob encode and decode a struct.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[3,7]]'::jsonb,'[3,7]',false,1),('[[-5,10]]'::jsonb,'[-5,10]',false,2),('[[0,0]]'::jsonb,'[0,0]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Linked Lists
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('reverse-linked-list','Linked Lists','function','go','Reverse Linked List','Given a slice of values, build a singly-linked list, reverse it, and return the values as a slice.','ReverseLinkedList','[]int',ARRAY['[]int']::text[],ARRAY['Define Node struct with Val int and Next *Node.','Build list, then reverse: prev=nil, current=head. Track next, point current.Next to prev, move forward.','Collect values from reversed list into a slice.'],2,100,ARRAY['linked-list','pointers','reverse','medium'],true,'MANUAL:reverse-linked-list',$$Reverse a singly-linked list.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3,4,5]]'::jsonb,'[5,4,3,2,1]',false,1),('[[1,2]]'::jsonb,'[2,1]',false,2),('[[1]]'::jsonb,'[1]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('merge-sorted-lists','Linked Lists','function','go','Merge Two Sorted Linked Lists','Given two slices representing sorted linked lists, merge them into one sorted linked list and return values as a slice.','MergeSortedLists','[]int',ARRAY['[]int','[]int']::text[],ARRAY['Build two sorted linked lists from the input slices.','Use two pointers: compare node values, take the smaller one.','If one list is exhausted, append the rest of the other list.'],2,110,ARRAY['linked-list','sorting','merge','medium'],true,'MANUAL:merge-sorted-lists',$$Merge two sorted linked lists into one.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,4],[1,3,4]]'::jsonb,'[1,1,2,3,4,4]',false,1),('[[],[0]]'::jsonb,'[0]',false,2),('[[],[]]'::jsonb,'[]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('has-cycle','Linked Lists','function','go','Linked List Cycle','Given a slice of values and a "cycle position" pos, build a linked list. If pos >= 0, the tail connects to the node at index pos. Return true if a cycle exists.','HasCycle','bool',ARRAY['[]int','int']::text[],ARRAY['Floyd tortoise and hare algorithm: slow moves 1 step, fast moves 2 steps.','If fast and slow meet, a cycle exists.','Build the list first, then connect the tail to the node at position pos (if pos >= 0).'],3,120,ARRAY['linked-list','cycle','two-pointers','medium'],true,'MANUAL:has-cycle',$$Detect if a linked list has a cycle.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[3,2,0,-4],1]'::jsonb,'true',false,1),('[[1,2],0]'::jsonb,'true',false,2),('[[1],-1]'::jsonb,'false',false,3),('[[],-1]'::jsonb,'false',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('remove-nth-from-end','Linked Lists','function','go','Remove Nth From End','Given a slice of values and n, build a linked list, remove the nth node from the end, and return the resulting list values.','RemoveNthFromEnd','[]int',ARRAY['[]int','int']::text[],ARRAY['Use two pointers: fast moves n steps ahead, then both move until fast reaches the end.','Slow pointer is at the node before the one to delete.','Handle edge case: removing the head node.'],3,120,ARRAY['linked-list','two-pointers','medium'],true,'MANUAL:remove-nth-from-end',$$Remove the nth node from the end of a linked list.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3,4,5],2]'::jsonb,'[1,2,3,5]',false,1),('[[1],1]'::jsonb,'[]',false,2),('[[1,2],1]'::jsonb,'[1]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('find-middle','Linked Lists','function','go','Middle of Linked List','Given a slice of values, build a linked list and return the middle node(s). If there are two middle nodes, return the second one. Values as slice.','FindMiddle','[]int',ARRAY['[]int']::text[],ARRAY['Tortoise and hare: slow moves 1 step, fast moves 2 steps.','When fast reaches the end, slow is at the middle.','Return the tail of the list starting from the middle node.'],1,50,ARRAY['linked-list','two-pointers','basic'],true,'MANUAL:find-middle',$$Find the middle node of a linked list.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3,4,5]]'::jsonb,'[3,4,5]',false,1),('[[1,2,3,4,5,6]]'::jsonb,'[4,5,6]',false,2),('[[1]]'::jsonb,'[1]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('intersection-of-two-ll','Linked Lists','function','go','Intersection of Two Linked Lists','Given two slices, build two linked lists that intersect at a given node. Return the value of the intersection node, or -1 if they do not intersect.','GetIntersectionNode','int',ARRAY['[]int','[]int','int']::text[],ARRAY['Build list A and B, then attach the tail of each to a common suffix starting at the intersection node.','Align both lists by trimming the longer one.','Traverse both together; the first equal node is the intersection.'],3,130,ARRAY['linked-list','two-pointers','medium'],true,'MANUAL:intersection-of-two-ll',$$Find the intersection node of two linked lists.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[4,1,8,4,5],[5,6,1,8,4,5],2]'::jsonb,'8',false,1),('[[1,9,1,2,4],[3,2,4],3]'::jsonb,'2',false,2),('[[2,6,4],[1,5],-1]'::jsonb,'-1',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- NOTE: For the Linked Lists intersection problem, the parameters are:
--   input = [listA_values, listB_values, intersection_position_in_A]
--   where the second list shares the suffix starting at that position in A.
--   -1 means no intersection.
-- =============================================================================
