-- =============================================================================
-- MODULE: Strings & Runes
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('reverse-words','Strings & Runes','function','go','Reverse Words','Given a string, reverse the order of words. A word is a sequence of non-space characters. Reduce multiple spaces to a single space and trim leading/trailing spaces.','ReverseWords','string',ARRAY['string']::text[],ARRAY['Split the string on spaces and collect non-empty tokens.','Reverse the token slice then rejoin with single spaces.','Use strings.Fields to handle whitespace automatically.'],2,90,ARRAY['strings','words','medium'],true,'MANUAL:reverse-words',$$Reverse the order of words in a string.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["the sky is blue"]'::jsonb,'"blue is sky the"',false,1),('["  hello   world  "]'::jsonb,'"world hello"',false,2),('["a good   example"]'::jsonb,'"example good a"',false,3),('[""]'::jsonb,'""',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('is-anagram','Strings & Runes','function','go','Valid Anagram','Given two strings s and t, return true if t is an anagram of s, false otherwise.','IsAnagram','bool',ARRAY['string','string']::text[],ARRAY['An anagram has the same character counts.','Use a frequency map or an array of 26 zeroes for lowercase letters.','Strings may contain Unicode; normalise to lowercase.'],1,60,ARRAY['strings','hashmap','basic'],true,'MANUAL:is-anagram',$$Check if two strings are anagrams.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["anagram","nagaram"]'::jsonb,'true',false,1),('["rat","car"]'::jsonb,'false',false,2),('["",""]'::jsonb,'true',false,3),('["a","aa"]'::jsonb,'false',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('is-palindrome','Strings & Runes','function','go','Is Palindrome','Return true if the given string reads the same forwards and backwards, false otherwise. Compare only alphanumeric characters and ignore case.','IsPalindrome','bool',ARRAY['string']::text[],ARRAY['Use two pointers moving from both ends toward the centre.','Skip non-alphanumeric characters using unicode.IsLetter/IsDigit.','Convert characters to lowercase before comparing.'],1,60,ARRAY['strings','two-pointers','basic'],true,'MANUAL:is-palindrome',$$Check whether a string is a palindrome.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["A man, a plan, a canal: Panama"]'::jsonb,'true',false,1),('["race a car"]'::jsonb,'false',false,2),('[" "]'::jsonb,'true',false,3),('["0P"]'::jsonb,'false',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('first-unique-char','Strings & Runes','function','go','First Unique Character','Given a string, find the index of the first non-repeating character and return it. If no unique character exists, return -1.','FirstUniqueChar','int',ARRAY['string']::text[],ARRAY['Count frequencies of each character first.','Iterate the string a second time; return the first index with count 1.','Use a map[rune]int for full Unicode support.'],2,90,ARRAY['strings','hashmap','medium'],true,'MANUAL:first-unique-char',$$Find the first non-repeating character index.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["leetcode"]'::jsonb,'0',false,1),('["loveleetcode"]'::jsonb,'2',false,2),('["aabb"]'::jsonb,'-1',false,3),('[""]'::jsonb,'-1',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('rune-frequency','Strings & Runes','function','go','Rune Frequency','Return a map counting each rune (character) in the input string.','RuneFrequency','map[string]int',ARRAY['string']::text[],ARRAY['Iterate over the string using range to get runes.','Increment a map[string]int entry for each rune.','Empty string returns an empty map.'],1,60,ARRAY['strings','runes','maps','basic'],true,'MANUAL:rune-frequency',$$Count rune frequency in a string.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["hello"]'::jsonb,'{"h":1,"e":1,"l":2,"o":1}',false,1),('["golang"]'::jsonb,'{"g":1,"o":1,"l":1,"a":1,"n":1}',false,2),('[""]'::jsonb,'{}',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('compress-string','Strings & Runes','function','go','String Compression','Compress a string by replacing runs of identical characters with the character followed by the count. If the compressed string is not shorter, return the original.','CompressString','string',ARRAY['string']::text[],ARRAY['Iterate through the string counting consecutive identical characters.','Append the character only if count > 1 after the first occurrence.','Compare lengths at the end to decide which to return.'],2,100,ARRAY['strings','compression','medium'],true,'MANUAL:compress-string',$$Compress repeated characters with count.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["aabcccccaaa"]'::jsonb,'"a2b1c5a3"',false,1),('["abcdef"]'::jsonb,'"abcdef"',false,2),('["aabb"]'::jsonb,'"aabb"',false,3),('[""]'::jsonb,'""',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('strstr','Strings & Runes','function','go','Find Substring','Return the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.','StrStr','int',ARRAY['string','string']::text[],ARRAY['Slide a window of length len(needle) over haystack.','Optimise by stopping early when insufficient characters remain.','An empty needle returns 0.'],2,90,ARRAY['strings','searching','medium'],true,'MANUAL:strstr',$$Find the first occurrence of a substring.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["sadbutsad","sad"]'::jsonb,'0',false,1),('["leetcode","leeto"]'::jsonb,'-1',false,2),('["hello",""]'::jsonb,'0',false,3),('["abc","c"]'::jsonb,'2',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('roman-to-int','Strings & Runes','function','go','Roman to Integer','Convert a Roman numeral string to an integer. Input is guaranteed to be valid and in range 1-3999.','RomanToInt','int',ARRAY['string']::text[],ARRAY['Map characters to values: I=1, V=5, X=10, L=50, C=100, D=500, M=1000.','If a smaller value appears before a larger one, subtract it.','Otherwise add the value.'],2,110,ARRAY['strings','numbers','medium'],true,'MANUAL:roman-to-int',$$Convert Roman numeral to integer.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["III"]'::jsonb,'3',false,1),('["LVIII"]'::jsonb,'58',false,2),('["MCMXCIV"]'::jsonb,'1994',false,3),('["IV"]'::jsonb,'4',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('caesar-cipher','Strings & Runes','function','go','Caesar Cipher','Encrypt a string by shifting each letter by k positions in the alphabet (A-Z, a-z). Preserve case. Non-letter characters pass through unchanged.','CaesarCipher','string',ARRAY['string','int']::text[],ARRAY['Normalise k to the range 0-25 using modulo.','Check if a rune is uppercase or lowercase to determine the base.','Use (rune - base + k) % 26 + base formula.'],2,90,ARRAY['strings','cipher','medium'],true,'MANUAL:caesar-cipher',$$Shift letters by k positions in the alphabet.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["abc",3]'::jsonb,'"def"',false,1),('["XYZ",3]'::jsonb,'"ABC"',false,2),('["Hello, World!",5]'::jsonb,'"Mjqqt, Btwqi!"',false,3),('["abc",26]'::jsonb,'"abc"',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('length-of-last-word','Strings & Runes','function','go','Length of Last Word','Given a string consisting of words and spaces, return the length of the last word. A word is a maximal substring of non-space characters.','LengthOfLastWord','int',ARRAY['string']::text[],ARRAY['Trim trailing spaces first.','Start from the end and count until hitting a space.','Edge case: a single word with no spaces.'],1,50,ARRAY['strings','basic'],true,'MANUAL:length-of-last-word',$$Return the length of the last word in a string.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["Hello World"]'::jsonb,'5',false,1),('["   fly me   to   the moon  "]'::jsonb,'4',false,2),('["luffy is still joyboy"]'::jsonb,'6',false,3),('["a"]'::jsonb,'1',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Math & Recursion
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('factorial','Math & Recursion','function','go','Factorial','Return n! (n factorial) for a non-negative integer n. 0! = 1.','Factorial','int',ARRAY['int']::text[],ARRAY['Base case: 0! = 1 and 1! = 1.','Use recursion: n! = n * (n-1)! for n > 1.','Be careful with large n; assume n <= 12 for int overflow safety.'],1,50,ARRAY['math','recursion','basic'],true,'MANUAL:factorial',$$Compute n factorial recursively.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[5]'::jsonb,'120',false,1),('[0]'::jsonb,'1',false,2),('[1]'::jsonb,'1',false,3),('[10]'::jsonb,'3628800',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('fibonacci','Math & Recursion','function','go','Fibonacci','Return the n-th number in the Fibonacci sequence (0-indexed). F(0) = 0, F(1) = 1, F(n) = F(n-1) + F(n-2).','Fibonacci','int',ARRAY['int']::text[],ARRAY['Base cases: F(0)=0, F(1)=1.','Use memoisation for efficiency if using recursion.','Iterative approach is O(n) time, O(1) space.'],1,50,ARRAY['math','recursion','basic'],true,'MANUAL:fibonacci',$$Compute the n-th Fibonacci number.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[2]'::jsonb,'1',false,1),('[3]'::jsonb,'2',false,2),('[10]'::jsonb,'55',false,3),('[0]'::jsonb,'0',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('gcd','Math & Recursion','function','go','Greatest Common Divisor','Return the greatest common divisor of two non-negative integers using Euclid algorithm.','GCD','int',ARRAY['int','int']::text[],ARRAY['If b=0, return a. Otherwise recurse with GCD(b, a%b).','Works for positive integers; if both are 0 return 0.','Euclid algorithm converges in O(log min(a,b)) steps.'],1,60,ARRAY['math','recursion','basic'],true,'MANUAL:gcd',$$Compute the greatest common divisor using Euclid algorithm.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[12,8]'::jsonb,'4',false,1),('[17,5]'::jsonb,'1',false,2),('[100,25]'::jsonb,'25',false,3),('[0,5]'::jsonb,'5',true,4),('[0,0]'::jsonb,'0',true,5)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('lcm','Math & Recursion','function','go','Least Common Multiple','Return the least common multiple of two non-negative integers.','LCM','int',ARRAY['int','int']::text[],ARRAY['LCM(a,b) = a * b / GCD(a,b).','Be careful of overflow -- cast to int64 or use division before multiplication.','If either a or b is 0, LCM is 0.'],1,60,ARRAY['math','numbers','basic'],true,'MANUAL:lcm',$$Compute the least common multiple of two numbers.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[4,6]'::jsonb,'12',false,1),('[7,13]'::jsonb,'91',false,2),('[12,18]'::jsonb,'36',false,3),('[0,5]'::jsonb,'0',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('digit-sum','Math & Recursion','function','go','Sum of Digits','Return the sum of the digits of a non-negative integer.','DigitSum','int',ARRAY['int']::text[],ARRAY['Repeatedly extract the last digit with n % 10 and add to sum.','Divide n by 10 to remove the last digit.','For n=0 return 0.'],1,40,ARRAY['math','numbers','basic'],true,'MANUAL:digit-sum',$$Sum the digits of a non-negative integer.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[123]'::jsonb,'6',false,1),('[9999]'::jsonb,'36',false,2),('[0]'::jsonb,'0',false,3),('[1001]'::jsonb,'2',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('power-of','Math & Recursion','function','go','Power Of','Compute base raised to the power of exp (non-negative integer exponent). Return 0^0 = 1.','PowerOf','int',ARRAY['int','int']::text[],ARRAY['Base case: x^0 = 1.','Use exponentiation by squaring for efficiency.','Handle negative base correctly (sign alternates with exponent parity).'],2,80,ARRAY['math','recursion','medium'],true,'MANUAL:power-of',$$Compute base^exp for integer exponent.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[2,3]'::jsonb,'8',false,1),('[5,0]'::jsonb,'1',false,2),('[0,0]'::jsonb,'1',false,3),('[-2,3]'::jsonb,'-8',true,4),('[2,10]'::jsonb,'1024',true,5)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('collatz-steps','Math & Recursion','function','go','Collatz Steps','Given a positive integer n, return the number of steps to reach 1: if n is even divide by 2, else multiply by 3 and add 1.','CollatzSteps','int',ARRAY['int']::text[],ARRAY['Base case: when n=1, return 0.','Recursively compute: if even -> n/2, if odd -> 3n+1.','Assume the conjecture holds for all inputs up to 10^6.'],2,80,ARRAY['math','recursion','medium'],true,'MANUAL:collatz-steps',$$Count steps to reach 1 following the Collatz sequence.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[1]'::jsonb,'0',false,1),('[12]'::jsonb,'9',false,2),('[6]'::jsonb,'8',false,3),('[2]'::jsonb,'1',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('perfect-number','Math & Recursion','function','go','Perfect Number','A perfect number equals the sum of its proper positive divisors. Return true if n is perfect, false otherwise.','IsPerfect','bool',ARRAY['int']::text[],ARRAY['A proper divisor excludes the number itself.','Check divisors from 1 to sqrt(n) for efficiency.','6, 28, 496 are the first three perfect numbers.'],2,80,ARRAY['math','numbers','medium'],true,'MANUAL:perfect-number',$$Check whether a number is perfect.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[6]'::jsonb,'true',false,1),('[28]'::jsonb,'true',false,2),('[12]'::jsonb,'false',false,3),('[1]'::jsonb,'false',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('sieve-of-eratosthenes','Math & Recursion','function','go','Sieve of Eratosthenes','Return all prime numbers less than or equal to n. Return empty slice if n < 2.','SieveOfEratosthenes','[]int',ARRAY['int']::text[],ARRAY['Create a boolean array of size n+1 initialised to true.','Mark multiples of each prime starting from 2.','Collect indices still marked true after sieving.'],2,100,ARRAY['math','primes','medium'],true,'MANUAL:sieve-of-eratosthenes',$$Generate primes up to n using the Sieve.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[10]'::jsonb,'[2,3,5,7]',false,1),('[2]'::jsonb,'[2]',false,2),('[1]'::jsonb,'[]',false,3),('[30]'::jsonb,'[2,3,5,7,11,13,17,19,23,29]',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('binomial-coefficient','Math & Recursion','function','go','Binomial Coefficient','Compute C(n,k), the number of ways to choose k elements from n elements. Return 0 if k is out of range.','Binomial','int',ARRAY['int','int']::text[],ARRAY['Use recurrence: C(n,k) = C(n-1,k-1) + C(n-1,k).','Base cases: C(n,0)=1, C(n,n)=1, C(n,k)=0 if k<0 or k>n.','Use memoisation or Pascal triangle for efficiency.'],2,100,ARRAY['math','recursion','combinatorics','medium'],true,'MANUAL:binomial-coefficient',$$Compute binomial coefficient C(n,k).$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[5,2]'::jsonb,'10',false,1),('[10,3]'::jsonb,'120',false,2),('[4,4]'::jsonb,'1',false,3),('[5,6]'::jsonb,'0',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('armstrong-number','Math & Recursion','function','go','Armstrong Number','An Armstrong number is an n-digit number equal to the sum of its digits each raised to power n. Return true if the given integer is an Armstrong number.','IsArmstrong','bool',ARRAY['int']::text[],ARRAY['Count the number of digits first.','Extract each digit, raise it to the power of digit count, and sum.','153 = 1^3 + 5^3 + 3^3 is a classic example.'],1,60,ARRAY['math','numbers','basic'],true,'MANUAL:armstrong-number',$$Check whether a number is an Armstrong number.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[153]'::jsonb,'true',false,1),('[9474]'::jsonb,'true',false,2),('[123]'::jsonb,'false',false,3),('[0]'::jsonb,'true',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Data Structures
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('next-greater-element','Data Structures','function','go','Next Greater Element','Given an integer slice, return a slice where result[i] is the next greater element to the right of nums[i], or -1 if none exists.','NextGreaterElement','[]int',ARRAY['[]int']::text[],ARRAY['Use a stack to track indices waiting for a greater element.','Iterate left to right; while current > nums[stack.top], pop and set result.','Elements without a greater neighbour stay -1.'],2,100,ARRAY['arrays','stack','monotonic','medium'],true,'MANUAL:next-greater-element',$$Find the next greater element for each position.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[4,1,2,1,3]]'::jsonb,'[-1,2,3,3,-1]',false,1),('[[1,2,3,4]]'::jsonb,'[2,3,4,-1]',false,2),('[[4,3,2,1]]'::jsonb,'[-1,-1,-1,-1]',false,3),('[[]]'::jsonb,'[]',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('daily-temperatures','Data Structures','function','go','Daily Temperatures','Given a slice of daily temperatures, for each day return how many days to wait until a warmer temperature. If none, return 0.','DailyTemperatures','[]int',ARRAY['[]int']::text[],ARRAY['Use a stack storing indices of days with decreasing temperatures.','When a warmer temperature is found, pop from stack and compute days difference.','If stack is non-empty at the end, remaining days get 0.'],3,130,ARRAY['arrays','stack','monotonic','medium'],true,'MANUAL:daily-temperatures',$$Compute days until warmer temperature for each day.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[73,74,75,71,69,72,76,73]]'::jsonb,'[1,1,4,2,1,1,0,0]',false,1),('[[30,40,50,60]]'::jsonb,'[1,1,1,0]',false,2),('[[90,80,70,60]]'::jsonb,'[0,0,0,0]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('max-sliding-window','Data Structures','function','go','Sliding Window Maximum','Given an integer slice and window size k, return the maximum element in every contiguous subarray of size k.','MaxSlidingWindow','[]int',ARRAY['[]int','int']::text[],ARRAY['Use a deque storing indices; maintain decreasing values.','Remove indices outside the window from the front.','The front of the deque is always the max of the current window.'],3,150,ARRAY['arrays','deque','sliding-window','medium'],true,'MANUAL:max-sliding-window',$$Find maximum in every sliding window of size k.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,3,-1,-3,5,3,6,7],3]'::jsonb,'[3,3,5,5,6,7]',false,1),('[[1],1]'::jsonb,'[1]',false,2),('[[1,-1],1]'::jsonb,'[1,-1]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;
