-- =============================================================================
-- MODULE: Dynamic Programming
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('coin-change','Dynamic Programming','function','go','Coin Change','Given a slice of coin denominations and a target amount, return the minimum number of coins to make that amount. Return -1 if impossible.','CoinChange','int',ARRAY['[]int','int']::text[],ARRAY['DP[i] = minimum coins to make amount i. Initialise DP[0]=0, rest=max.','For each coin, DP[i] = min(DP[i], DP[i-coin]+1).','If DP[amount] is still max, return -1.'],3,150,ARRAY['dp','optimisation','medium'],true,'MANUAL:coin-change',$$Minimum coins to make a target amount.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,5],11]'::jsonb,'3',false,1),('[[2],3]'::jsonb,'-1',false,2),('[[1],0]'::jsonb,'0',false,3),('[[1,3,4,5],7]'::jsonb,'2',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('longest-increasing-subseq','Dynamic Programming','function','go','Longest Increasing Subsequence','Given an integer slice, return the length of the longest strictly increasing subsequence.','LIS','int',ARRAY['[]int']::text[],ARRAY['DP[i] = LIS ending at index i. Initialise all to 1.','For each i, check all j < i; if nums[j] < nums[i], DP[i] = max(DP[i], DP[j]+1).','Return max of DP array (or 0 for empty input).'],3,140,ARRAY['dp','subsequence','medium'],true,'MANUAL:longest-increasing-subseq',$$Length of the longest increasing subsequence.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[10,9,2,5,3,7,101,18]]'::jsonb,'4',false,1),('[[0,1,0,3,2,3]]'::jsonb,'4',false,2),('[[7,7,7,7]]'::jsonb,'1',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('climbing-stairs','Dynamic Programming','function','go','Climbing Stairs','You climb a staircase of n steps. Each time you can take 1 or 2 steps. Return the number of distinct ways to reach the top.','ClimbingStairs','int',ARRAY['int']::text[],ARRAY['DP[i] = ways to reach step i. DP[1]=1, DP[2]=2.','DP[i] = DP[i-1] + DP[i-2] (this is Fibonacci-like).','Base cases: n=0 yields 0, n=1 yields 1, n=2 yields 2.'],1,50,ARRAY['dp','fibonacci','basic'],true,'MANUAL:climbing-stairs',$$Count ways to climb n steps (1 or 2 steps at a time).$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[2]'::jsonb,'2',false,1),('[3]'::jsonb,'3',false,2),('[5]'::jsonb,'8',false,3),('[1]'::jsonb,'1',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('edit-distance','Dynamic Programming','function','go','Edit Distance','Return the minimum number of operations (insert, delete, replace) to convert string word1 into string word2.','EditDistance','int',ARRAY['string','string']::text[],ARRAY['DP[i][j] = edit distance between word1[0:i] and word2[0:j].','If characters match: DP[i][j] = DP[i-1][j-1].','Else: DP[i][j] = 1 + min(insert, delete, replace).'],4,200,ARRAY['dp','strings','hard'],true,'MANUAL:edit-distance',$$Minimum edit distance between two strings.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["horse","ros"]'::jsonb,'3',false,1),('["intention","execution"]'::jsonb,'5',false,2),('["","a"]'::jsonb,'1',false,3),('["abc","abc"]'::jsonb,'0',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('knapsack','Dynamic Programming','function','go','0/1 Knapsack','Given a slice of item weights and corresponding values, and a knapsack capacity, return the maximum total value possible.','Knapsack','int',ARRAY['[]int','[]int','int']::text[],ARRAY['DP[i][w] = max value using first i items with capacity w.','For each item, either skip it (DP[i-1][w]) or take it (DP[i-1][w-weight[i]] + value[i]).','Return DP[n][capacity].'],3,160,ARRAY['dp','knapsack','optimisation','medium'],true,'MANUAL:knapsack',$$Solve the 0/1 knapsack problem.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3],[6,10,12],5]'::jsonb,'22',false,1),('[[2,3,4],[3,4,5],5]'::jsonb,'7',false,2),('[[1,2,3],[10,15,40],6]'::jsonb,'50',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('max-product-subarray','Dynamic Programming','function','go','Maximum Product Subarray','Given an integer slice, find the contiguous subarray with the largest product and return the product.','MaxProductSubarray','int',ARRAY['[]int']::text[],ARRAY['Track both max and min product ending at each index (due to negative numbers).','If current number is negative, swap max and min before multiplying.','Update the global maximum after each step.'],3,150,ARRAY['dp','arrays','medium'],true,'MANUAL:max-product-subarray',$$Maximum product of a contiguous subarray.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[2,3,-2,4]]'::jsonb,'6',false,1),('[[-2,0,-1]]'::jsonb,'0',false,2),('[[-2,3,-4]]'::jsonb,'24',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('palindrome-partitioning','Dynamic Programming','function','go','Palindrome Partitioning','Given a string, partition it into substrings such that every substring is a palindrome. Return ALL possible palindrome partitions.','PalindromePartition','[][]string',ARRAY['string']::text[],ARRAY['Use backtracking + DP for palindrome checks.','Precompute isPalindrome[i][j] for all substrings via DP.','At each step, extend the current partition with a palindrome substring.'],4,190,ARRAY['dp','backtracking','strings','hard'],true,'MANUAL:palindrome-partitioning',$$Return all palindrome partitions of a string.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["aab"]'::jsonb,'[["a","a","b"],["aa","b"]]',false,1),('["a"]'::jsonb,'[["a"]]',false,2),('[""]'::jsonb,'[[""]]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('word-break','Dynamic Programming','function','go','Word Break','Given a string and a dictionary of strings ([]string), return true if the string can be segmented into dictionary words.','WordBreak','bool',ARRAY['string','[]string']::text[],ARRAY['DP[i] = true if s[0:i] can be segmented. Initialise DP[0]=true.','For each i, check all j < i: if DP[j] and s[j:i] is in wordDict, set DP[i]=true.','Use a map for O(1) dictionary lookups.'],3,150,ARRAY['dp','strings','medium'],true,'MANUAL:word-break',$$Check if a string can be segmented into dictionary words.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["leetcode",["leet","code"]]'::jsonb,'true',false,1),('["applepenapple",["apple","pen"]]'::jsonb,'true',false,2),('["catsandog",["cats","dog","sand","and","cat"]]'::jsonb,'false',false,3),('["",["a"]]'::jsonb,'true',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Bit Manipulation
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('hamming-weight','Bit Manipulation','function','go','Hamming Weight','Return the number of 1 bits (set bits) in the binary representation of a non-negative integer.','HammingWeight','int',ARRAY['int']::text[],ARRAY['Use n & (n-1) to clear the lowest set bit repeatedly.','Count how many times you can do this until n becomes 0.','Alternatively, shift right and check LSB, but n & (n-1) is more efficient.'],1,50,ARRAY['bits','basic'],true,'MANUAL:hamming-weight',$$Count set bits (1s) in binary representation.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[11]'::jsonb,'3',false,1),('[128]'::jsonb,'1',false,2),('[2147483645]'::jsonb,'30',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('single-number','Bit Manipulation','function','go','Single Number','Given a slice where every element appears twice except one, find the element that appears once.','SingleNumber','int',ARRAY['[]int']::text[],ARRAY['XOR all numbers together: a XOR a = 0, a XOR 0 = a.','Duplicate pairs cancel out.','The remaining value is the single number.'],1,50,ARRAY['bits','xor','arrays','basic'],true,'MANUAL:single-number',$$Find the element that appears once when all others appear twice.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[2,2,1]]'::jsonb,'1',false,1),('[[4,1,2,1,2]]'::jsonb,'4',false,2),('[[1]]'::jsonb,'1',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('power-of-two','Bit Manipulation','function','go','Power of Two','Return true if n is a power of two, false otherwise.','PowerOfTwo','bool',ARRAY['int']::text[],ARRAY['A power of two has exactly one set bit.','Use n > 0 && (n & (n-1)) == 0 to check.','Edge cases: n=0 is false, n=1 is true (2^0).'],1,40,ARRAY['bits','math','basic'],true,'MANUAL:power-of-two',$$Check if a number is a power of two.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[1]'::jsonb,'true',false,1),('[16]'::jsonb,'true',false,2),('[218]'::jsonb,'false',false,3),('[0]'::jsonb,'false',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('bit-reverse','Bit Manipulation','function','go','Reverse Bits','Reverse the bits of a given 32-bit unsigned integer and return the result.','ReverseBits','int',ARRAY['int']::text[],ARRAY['Iterate through all 32 bits of the input.','Shift result left, add the LSB of n, then shift n right.','Be careful with sign extension; treat as uint32 if needed.'],2,100,ARRAY['bits','medium'],true,'MANUAL:bit-reverse',$$Reverse the bits of a 32-bit unsigned integer.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[43261596]'::jsonb,'964176192',false,1),('[4294967293]'::jsonb,'3221225471',false,2),('[0]'::jsonb,'0',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('find-difference','Bit Manipulation','function','go','Find the Difference','Given two strings s and t where t is generated by randomly shuffling s and adding one extra character, find the added character.','FindTheDifference','byte',ARRAY['string','string']::text[],ARRAY['XOR all bytes from both strings together.','Every character appearing in both will XOR to 0.','The remaining byte is the extra character.'],1,50,ARRAY['bits','xor','strings','basic'],true,'MANUAL:find-difference',$$Find the character added to one string vs another.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["abcd","abcde"]'::jsonb,'"e"',false,1),('["","y"]'::jsonb,'"y"',false,2),('["a","aa"]'::jsonb,'"a"',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('has-alternating-bits','Bit Manipulation','function','go','Alternating Bits','Return true if the binary representation of n has alternating bits (every pair of adjacent bits differ).','HasAlternatingBits','bool',ARRAY['int']::text[],ARRAY['Compute n XOR (n>>1). If the result has all bits set to 1, the original has alternating bits.','Check if (n XOR n>>1) is a power of two minus 1.','For example: 5 (101) -> 101 XOR 010 = 111 (which is 2^3-1).'],1,60,ARRAY['bits','basic'],true,'MANUAL:has-alternating-bits',$$Check if a number has alternating bits.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[5]'::jsonb,'true',false,1),('[7]'::jsonb,'false',false,2),('[11]'::jsonb,'false',false,3),('[0]'::jsonb,'true',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('subset-xor-sum','Bit Manipulation','function','go','XOR-Based Subset Sum','Given a slice of integers, return the sum of XORs of all subsets.','SubsetXORSum','int',ARRAY['[]int']::text[],ARRAY['Bitwise OR of all elements, then left shift by n-1 bits.','Each bit contributes 2^(n-1) * (that bit set in OR).','OR all elements to find which bits appear at least once.'],2,100,ARRAY['bits','xor','math','medium'],true,'MANUAL:subset-xor-sum',$$Sum of XOR totals of all subsets.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,3]]'::jsonb,'6',false,1),('[[5,1,6]]'::jsonb,'28',false,2),('[[1,2,3]]'::jsonb,'12',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Trees & Graphs
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('max-depth-bt','Trees & Graphs','function','go','Maximum Depth of Binary Tree','Given a binary tree represented as a slice in level order (with -1 as null), return its maximum depth.','MaxDepthBT','int',ARRAY['[]int']::text[],ARRAY['The root is at index 0. Children of node i are at 2i+1 and 2i+2.','Skip null nodes (-1) when computing children.','Use recursion: depth = 1 + max(depth(left), depth(right)).'],2,100,ARRAY['trees','binary-tree','recursion','medium'],true,'MANUAL:max-depth-bt',$$Find the maximum depth of a binary tree.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[3,9,20,-1,-1,15,7]]'::jsonb,'3',false,1),('[[1,-1,2]]'::jsonb,'2',false,2),('[[]]'::jsonb,'0',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('inorder-traversal','Trees & Graphs','function','go','Inorder Traversal','Given a binary tree represented as a level-order slice, return the inorder traversal as a slice.','InorderTraversal','[]int',ARRAY['[]int']::text[],ARRAY['Inorder visits: left, root, right.','Use a stack for iterative traversal or recursion.','Null nodes (-1) are skipped.'],2,80,ARRAY['trees','binary-tree','traversal','medium'],true,'MANUAL:inorder-traversal',$$Return the inorder traversal of a binary tree.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,-1,2,3]]'::jsonb,'[1,3,2]',false,1),('[[]]'::jsonb,'[]',false,2),('[[1,2,3,4,5]]'::jsonb,'[4,2,5,1,3]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('has-path-sum','Trees & Graphs','function','go','Path Sum','Given a binary tree level-order slice and a target sum, return true if there is a root-to-leaf path summing to target.','HasPathSum','bool',ARRAY['[]int','int']::text[],ARRAY['Subtract current node value from remaining sum on each recursion step.','If at a leaf (no children) and remaining sum is 0, return true.','Null nodes are skipped.'],2,100,ARRAY['trees','binary-tree','dfs','medium'],true,'MANUAL:has-path-sum',$$Check if there is a root-to-leaf path with a given sum.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[5,4,8,11,-1,13,4,7,2,-1,-1,-1,1],22]'::jsonb,'true',false,1),('[[1,2,3],5]'::jsonb,'false',false,2),('[[]]'::jsonb,'false',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('is-graph-bipartite','Trees & Graphs','function','go','Graph Bipartite','Given an adjacency list ([][]int), return true if the graph is bipartite.','IsBipartite','bool',ARRAY['[][]int']::text[],ARRAY['Two-color algorithm: assign 0 (uncolored), 1 (red), -1 (blue).','Use BFS: for each uncolored node, start BFS coloring neighbours opposite.','If a neighbour has the same color as current, return false.'],3,150,ARRAY['graphs','bfs','bipartite','medium'],true,'MANUAL:is-graph-bipartite',$$Check if a graph is bipartite.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[[1,2,3],[0,2],[0,1,3],[0,2]]]'::jsonb,'false',false,1),('[[[1,3],[0,2],[1,3],[0,2]]]'::jsonb,'true',false,2),('[[[1],[0],[3],[2]]]'::jsonb,'true',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('number-of-islands','Trees & Graphs','function','go','Number of Islands','Given a 2D grid (][]int) of 1s (land) and 0s (water), return the number of islands (connected 1s orthogonally).','NumIslands','int',ARRAY['[][]int']::text[],ARRAY['Iterate each cell; when land (1) is found, increment count and DFS/BFS to mark all connected land.','Mark visited land as 0 or use a visited set.','Use a closure or helper function for DFS traversal in 4 directions.'],3,140,ARRAY['graphs','dfs','bfs','grid','medium'],true,'MANUAL:number-of-islands',$$Count the number of islands in a 2D grid.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[[1,1,1,1,0],[1,1,0,1,0],[1,1,0,0,0],[0,0,0,0,0]]]'::jsonb,'1',false,1),('[[[1,1,0,0,0],[1,1,0,0,0],[0,0,1,0,0],[0,0,0,1,1]]]'::jsonb,'3',false,2),('[[[0,0,0],[0,0,0]]]'::jsonb,'0',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('is-valid-bst','Trees & Graphs','function','go','Validate Binary Search Tree','Given a level-order tree slice, return true if it is a valid BST (all left < root < right recursively).','IsValidBST','bool',ARRAY['[]int']::text[],ARRAY['Track min/max allowed value as you recurse.','Left subtree must be within (min, root.val) and right within (root.val, max).','Use -inf and +inf for the root range limits.'],3,130,ARRAY['trees','bst','validation','medium'],true,'MANUAL:is-valid-bst',$$Validate a binary search tree.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[2,1,3]]'::jsonb,'true',false,1),('[[5,1,4,-1,-1,3,6]]'::jsonb,'false',false,2),('[[2,2,2]]'::jsonb,'false',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;
