-- =============================================================================
-- seed_all_modules.sql
-- Seed ~180 function-type Go problems across 18 modules.
-- ON CONFLICT (slug) DO NOTHING — safe to re-run.
-- source_hash prefix "MANUAL:" marks rows as hand-authored.
-- =============================================================================

-- =============================================================================
-- MODULE: Arrays & Slices
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('reverse-slice','Arrays & Slices','function','go','Reverse Slice','Given an integer slice, return a new slice with elements in reverse order. Do not mutate the input.','ReverseSlice','[]int',ARRAY['[]int']::text[],ARRAY['Swap elements from both ends toward the centre.','Allocate a result slice of the same length first.','An empty slice should return an empty slice.'],1,60,ARRAY['arrays','slices','basic'],true,'MANUAL:reverse-slice',$$Return the reversed copy of the input slice.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3,4,5]]'::jsonb,'[5,4,3,2,1]',false,1),('[[1]]'::jsonb,'[1]',false,2),('[[]]'::jsonb,'[]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('slice-max','Arrays & Slices','function','go','Slice Maximum','Return the largest integer in the slice. Return 0 for an empty slice.','SliceMax','int',ARRAY['[]int']::text[],ARRAY['Initialise max with the first element when length > 0.','Handle negative numbers correctly.'],1,50,ARRAY['arrays','basic'],true,'MANUAL:slice-max',$$Find the maximum value in an integer slice.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[3,7,2,9,5]]'::jsonb,'9',false,1),('[[-5,-2,-8,-1]]'::jsonb,'-1',false,2),('[[42]]'::jsonb,'42',false,3),('[[]]'::jsonb,'0',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('rotate-left','Arrays & Slices','function','go','Rotate Left','Rotate the slice left by k positions. Elements shifted off the front wrap around to the back. If k is larger than the slice length, take k modulo len.','RotateLeft','[]int',ARRAY['[]int','int']::text[],ARRAY['Normalise k by taking k modulo n.','Use append on the two parts: slice[k:] + slice[:k].','Handle k=0 and empty slice as edge cases.'],2,80,ARRAY['arrays','rotation','medium'],true,'MANUAL:rotate-left',$$Rotate a slice left by k positions.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3,4,5],2]'::jsonb,'[3,4,5,1,2]',false,1),('[[1,2,3],0]'::jsonb,'[1,2,3]',false,2),('[[1,2],5]'::jsonb,'[2,1]',false,3),('[[]]'::jsonb,'[]',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('remove-duplicates','Arrays & Slices','function','go','Remove Duplicates','Given a sorted integer slice, remove duplicate elements in-place and return the new slice containing only unique elements preserving order.','RemoveDuplicates','[]int',ARRAY['[]int']::text[],ARRAY['Use two pointers: one for the write position and one for scanning.','Compare each element with the previous one; write only on first occurrence.','The input is guaranteed to be sorted in non-decreasing order.'],2,90,ARRAY['arrays','two-pointers','medium'],true,'MANUAL:remove-duplicates',$$Remove duplicates from a sorted slice.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,1,2]]'::jsonb,'[1,2]',false,1),('[[0,0,1,1,1,2,2,3,3,4]]'::jsonb,'[0,1,2,3,4]',false,2),('[[1,2,3]]'::jsonb,'[1,2,3]',false,3),('[[]]'::jsonb,'[]',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('chunk-slice','Arrays & Slices','function','go','Chunk Slice','Split an integer slice into sub-slices of at most size elements each. The last chunk may be smaller than size.','ChunkSlice','[][]int',ARRAY['[]int','int']::text[],ARRAY['Use a loop that advances by `size` each iteration.','Append full slices and handle the remainder at the end.','If size <= 0 return an empty result.'],2,90,ARRAY['arrays','iteration','medium'],true,'MANUAL:chunk-slice',$$Split a slice into fixed-size chunks.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3,4,5],2]'::jsonb,'[[1,2],[3,4],[5]]',false,1),('[[1,2,3],5]'::jsonb,'[[1,2,3]]',false,2),('[[1,2,3,4],1]'::jsonb,'[[1],[2],[3],[4]]',false,3),('[[]]'::jsonb,'[]',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('slice-intersection','Arrays & Slices','function','go','Slice Intersection','Return the intersection of two integer slices — elements that appear in both. The result should contain each unique element only once, in any order.','SliceIntersection','[]int',ARRAY['[]int','[]int']::text[],ARRAY['Use a map to record elements of the first slice.','Iterate the second slice and collect matches.','De-duplicate by removing from the map after adding to result.'],2,100,ARRAY['arrays','sets','medium'],true,'MANUAL:slice-intersection',$$Compute the set intersection of two slices.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3,4],[3,4,5,6]]'::jsonb,'[3,4]',false,1),('[[1,1,2,2],[2,2,3]]'::jsonb,'[2]',false,2),('[[1,2],[3,4]]'::jsonb,'[]',false,3),('[[],[]]'::jsonb,'[]',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('running-sum','Arrays & Slices','function','go','Running Sum','Return a slice where result[i] is the sum of all elements from index 0 to i in the input.','RunningSum','[]int',ARRAY['[]int']::text[],ARRAY['Initialise runningSum to 0 and update it as you iterate.','result[i] = runningSum + input[i].','An empty slice returns an empty slice.'],1,60,ARRAY['arrays','prefix-sum','basic'],true,'MANUAL:running-sum',$$Compute the running (cumulative) sum of a slice.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3,4]]'::jsonb,'[1,3,6,10]',false,1),('[[5,0,-5,10]]'::jsonb,'[5,5,0,10]',false,2),('[[10]]'::jsonb,'[10]',false,3),('[[]]'::jsonb,'[]',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('pivot-index','Arrays & Slices','function','go','Find Pivot Index','Given an integer slice, return the leftmost pivot index where the sum of all numbers to the left equals the sum of all numbers to the right. Return -1 if no such index exists.','PivotIndex','int',ARRAY['[]int']::text[],ARRAY['Compute the total sum first.','Iterate maintaining a left sum; the right sum is total - left - current.','Pivot index can be 0 or len-1.'],2,100,ARRAY['arrays','prefix-sum','medium'],true,'MANUAL:pivot-index',$$Find the index where left-sum equals right-sum.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,7,3,6,5,6]]'::jsonb,'3',false,1),('[[1,2,3]]'::jsonb,'-1',false,2),('[[2,1,-1]]'::jsonb,'0',false,3),('[[]]'::jsonb,'-1',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('max-subarray','Arrays & Slices','function','go','Maximum Subarray Sum','Given an integer slice, find the contiguous subarray with the largest sum and return that sum.','MaxSubarray','int',ARRAY['[]int']::text[],ARRAY['Use Kadane algorithm: keep current max ending here and global max.','If current sum drops below 0, reset to 0 (or restart at next element).','An empty slice returns 0.'],3,140,ARRAY['arrays','kadane','dp','medium'],true,'MANUAL:max-subarray',$$Find the maximum subarray sum using Kadane algorithm.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[-2,1,-3,4,-1,2,1,-5,4]]'::jsonb,'6',false,1),('[[1]]'::jsonb,'1',false,2),('[[5,4,-1,7,8]]'::jsonb,'23',false,3),('[[-1,-2,-3]]'::jsonb,'-1',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('spiral-order','Arrays & Slices','function','go','Spiral Matrix','Given an mxn matrix, return all elements in spiral order: right, down, left, up, repeating inward.','SpiralOrder','[]int',ARRAY['[][]int']::text[],ARRAY['Track four boundaries: top, bottom, left, right.','Shrink the boundary after each completed direction.','Stop when top exceeds bottom or left exceeds right.'],3,150,ARRAY['arrays','matrices','traversal','medium'],true,'MANUAL:spiral-order',$$Return matrix elements in clockwise spiral order.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[[1,2,3],[4,5,6],[7,8,9]]]'::jsonb,'[1,2,3,6,9,8,7,4,5]',false,1),('[[[1,2,3,4],[5,6,7,8]]]'::jsonb,'[1,2,3,4,8,7,6,5]',false,2),('[[[1]]]'::jsonb,'[1]',false,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;
