-- =============================================================================
-- MODULE: Data Structures (continued - Min Stack, Queue, Circular Buffer)
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('min-stack','Data Structures','function','go','Min Stack','Design a data structure that supports push, pop, top, and retrieving the minimum element in O(1) time. Return an evaluation string: "push|pop|top|getMin" actions.','MinStack','[]interface{}',ARRAY['[]string']::text[],ARRAY['Maintain two stacks: one for values and one for current minimums.','On push: if value <= current min, push to minStack too.','On pop: if popped value equals minStack top, pop minStack too.'],2,110,ARRAY['stack','design','medium'],true,'MANUAL:min-stack',$$Implement a stack with O(1) minimum retrieval.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[["push","push","push","getMin","pop","top","getMin"]]'::jsonb,'[null,null,null,-2,null,0,-1]',false,1),('[["push","push","getMin","pop","getMin"]]'::jsonb,'[null,null,-1,null,0]',true,2)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('my-queue','Data Structures','function','go','Implement Queue using Stacks','Implement a FIFO queue using two stacks. Return evaluation results for a series of operations.','MyQueue','[]interface{}',ARRAY['[]string']::text[],ARRAY['Use two stacks: inStack for pushes, outStack for pops/peeks.','When outStack is empty, transfer all elements from inStack to outStack.','This gives amortised O(1) per operation.'],2,100,ARRAY['queue','stack','design','medium'],true,'MANUAL:my-queue',$$Implement a FIFO queue using two stacks.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[["push","push","peek","pop","empty"]]'::jsonb,'[null,null,1,1,false]',false,1),('[["push","pop","push","peek","pop","empty"]]'::jsonb,'[null,null,null,1,1,true]',true,2)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('circular-buffer','Data Structures','function','go','Circular Buffer','Implement a circular buffer with fixed capacity. Return result slice after a series of read/write operations.','CircularBuffer','[]interface{}',ARRAY['int','[]string']::text[],ARRAY['Use a slice of fixed size, head and tail pointers.','Write advances tail; read advances head (both modulo capacity).','Return the buffer contents in order (head to tail).'],2,90,ARRAY['buffer','design','medium'],true,'MANUAL:circular-buffer',$$Implement a circular buffer with fixed capacity.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[3,["write","write","write","read","write","read","read"]]'::jsonb,'[1,2,3,1,4,2,3]',false,1),('[2,["write","write","write","read","read"]]'::jsonb,'[1,2,null,1,2]',true,2)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Sorting & Searching
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('merge-sorted','Sorting & Searching','function','go','Merge Sorted Arrays','Merge two sorted integer slices into one sorted slice.','MergeSorted','[]int',ARRAY['[]int','[]int']::text[],ARRAY['Use two pointers, one for each slice.','Compare elements at both pointers and append the smaller one.','If one list is exhausted, append the rest of the other list.'],1,60,ARRAY['arrays','sorting','two-pointers','basic'],true,'MANUAL:merge-sorted',$$Merge two sorted arrays into one sorted result.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3],[2,5,6]]'::jsonb,'[1,2,2,3,5,6]',false,1),('[[],[1]]'::jsonb,'[1]',false,2),('[[1,1,1],[1,1,1]]'::jsonb,'[1,1,1,1,1,1]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('binary-search','Sorting & Searching','function','go','Binary Search','Given a sorted integer slice and a target value, return the index of target. If not found, return -1.','BinarySearch','int',ARRAY['[]int','int']::text[],ARRAY['Maintain left and right pointers.','Mid = left + (right-left)/2 to avoid overflow.','If nums[mid] < target, search right half; else search left half.'],1,50,ARRAY['searching','binary-search','basic'],true,'MANUAL:binary-search',$$Binary search a target in a sorted array.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[-1,0,3,5,9,12],9]'::jsonb,'4',false,1),('[[-1,0,3,5,9,12],2]'::jsonb,'-1',false,2),('[[1],1]'::jsonb,'0',false,3),('[[],5]'::jsonb,'-1',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('find-peak','Sorting & Searching','function','go','Find Peak Element','A peak element is strictly greater than its neighbours. Return the index of any peak element.','FindPeak','int',ARRAY['[]int']::text[],ARRAY['Use binary search: if mid > mid+1, peak in left half; else right half.','The array may have multiple peaks; return any one.','Edge case: single element is a peak (index 0).'],2,90,ARRAY['searching','binary-search','peak','medium'],true,'MANUAL:find-peak',$$Find any peak element in an array.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3,1]]'::jsonb,'2',false,1),('[[1,2,1,3,5,6,4]]'::jsonb,'5',false,2),('[[1]]'::jsonb,'0',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('quick-sort','Sorting & Searching','function','go','Quick Sort','Implement quick sort to sort an integer slice in ascending order. Return the sorted slice.','QuickSort','[]int',ARRAY['[]int']::text[],ARRAY['Choose a pivot (e.g., last element).','Partition: elements < pivot on left, > pivot on right.','Recursively sort the left and right partitions.'],2,100,ARRAY['sorting','divide-conquer','medium'],true,'MANUAL:quick-sort',$$Implement quick sort algorithm.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[3,6,1,8,2,5]]'::jsonb,'[1,2,3,5,6,8]',false,1),('[[1]]'::jsonb,'[1]',false,2),('[[]]'::jsonb,'[]',true,3),('[[5,4,3,2,1]]'::jsonb,'[1,2,3,4,5]',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('first-bad-version','Sorting & Searching','function','go','First Bad Version','An API isBadVersion(n int) bool is provided. Find the first bad version in the range 1..n, minimising API calls.','FirstBadVersion','int',ARRAY['int']::text[],ARRAY['Classic binary search variant.','If mid is bad, search left; if not, search right.','Return the left pointer when loop ends.'],2,80,ARRAY['searching','binary-search','medium'],true,'MANUAL:first-bad-version',$$Find the first bad version using binary search.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[5]'::jsonb,'4',false,1),('[1]'::jsonb,'1',false,2),('[10]'::jsonb,'7',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('find-kth-smallest','Sorting & Searching','function','go','Kth Smallest Element','Given an unsorted integer slice, return the kth smallest element (1-indexed). You may modify the input.','KthSmallest','int',ARRAY['[]int','int']::text[],ARRAY['Use quick select: partition like quicksort, then recurse on the relevant half.','If pivot index == k-1, return it.','Average O(n) time, worst-case O(n^2).'],3,130,ARRAY['searching','quickselect','divide-conquer','medium'],true,'MANUAL:find-kth-smallest',$$Find kth smallest element using quick select.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[3,2,1,5,6,4],2]'::jsonb,'2',false,1),('[[3,2,3,1,2,4,5,5,6],4]'::jsonb,'3',false,2),('[[1],1]'::jsonb,'1',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('search-rotated','Sorting & Searching','function','go','Search in Rotated Sorted Array','A sorted array was rotated at an unknown pivot. Search for a target and return its index, or -1 if not found.','SearchRotated','int',ARRAY['[]int','int']::text[],ARRAY['Modified binary search: find which half is sorted.','If left half is sorted (nums[left] <= nums[mid]), check if target is in that range.','Otherwise check the right half.'],3,140,ARRAY['searching','binary-search','rotated','medium'],true,'MANUAL:search-rotated',$$Search in a rotated sorted array.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[4,5,6,7,0,1,2],0]'::jsonb,'4',false,1),('[[4,5,6,7,0,1,2],3]'::jsonb,'-1',false,2),('[[1],0]'::jsonb,'-1',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Hash Maps & Sets
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('two-sum','Hash Maps & Sets','function','go','Two Sum','Given a slice of integers and a target integer, return the indices of the two numbers that add up to target. Exactly one solution exists.','TwoSum','[]int',ARRAY['[]int','int']::text[],ARRAY['Use a map[value]index to store seen elements.','For each element, check if target - element exists in the map.','If found, return [map[complement], currentIndex].'],1,50,ARRAY['hashmap','arrays','basic'],true,'MANUAL:two-sum',$$Find two numbers that sum to target.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[2,7,11,15],9]'::jsonb,'[0,1]',false,1),('[[3,2,4],6]'::jsonb,'[1,2]',false,2),('[[3,3],6]'::jsonb,'[0,1]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('contains-duplicate','Hash Maps & Sets','function','go','Contains Duplicate','Return true if any value appears at least twice in the slice.','ContainsDuplicate','bool',ARRAY['[]int']::text[],ARRAY['Use a set (map[int]bool) to track seen values.','If a value is already in the set, return true.','If loop completes, return false.'],1,40,ARRAY['hashmap','arrays','basic'],true,'MANUAL:contains-duplicate',$$Check if any value appears more than once.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3,1]]'::jsonb,'true',false,1),('[[1,2,3,4]]'::jsonb,'false',false,2),('[[]]'::jsonb,'false',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('intersection-of-two','Hash Maps & Sets','function','go','Intersection of Two Arrays','Return the intersection of two integer slices (each element is unique).','Intersection','[]int',ARRAY['[]int','[]int']::text[],ARRAY['Store elements of the first slice in a set.','Iterate the second slice; if element is in the set, add to result and remove from set.','Return the result slice (unique values only).'],1,60,ARRAY['hashmap','sets','arrays','basic'],true,'MANUAL:intersection-of-two',$$Find the intersection of two arrays.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,2,1],[2,2]]'::jsonb,'[2]',false,1),('[[4,9,5],[9,4,9,8,4]]'::jsonb,'[9,4]',false,2),('[[1,2,3],[4,5,6]]'::jsonb,'[]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('group-anagrams','Hash Maps & Sets','function','go','Group Anagrams','Given a slice of strings, group anagrams together (order within groups does not matter).','GroupAnagrams','[][]string',ARRAY['[]string']::text[],ARRAY['Sort each string to use as the map key.','Alternatively, use a character frequency count as key.','Append each string to its group in the map.'],2,110,ARRAY['hashmap','strings','sorting','medium'],true,'MANUAL:group-anagrams',$$Group strings that are anagrams of each other.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[["eat","tea","tan","ate","nat","bat"]]'::jsonb,'[["eat","tea","ate"],["tan","nat"],["bat"]]',false,1),('[[""]]'::jsonb,'[[""]]',false,2),('[["a"]]'::jsonb,'[["a"]]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('longest-consecutive','Hash Maps & Sets','function','go','Longest Consecutive Sequence','Given an unsorted integer slice, return the length of the longest consecutive elements sequence. Must run in O(n).','LongestConsecutive','int',ARRAY['[]int']::text[],ARRAY['Add all numbers to a set.','For each number, check if num-1 is NOT in the set (start of a sequence).','Count consecutive numbers from each start and track the maximum length.'],3,140,ARRAY['hashmap','sets','arrays','medium'],true,'MANUAL:longest-consecutive',$$Find the length of the longest consecutive sequence.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[100,4,200,1,3,2]]'::jsonb,'4',false,1),('[[0,3,7,2,5,8,4,6,0,1]]'::jsonb,'9',false,2),('[[]]'::jsonb,'0',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('subarray-sum-equals','Hash Maps & Sets','function','go','Subarray Sum Equals K','Given an integer slice and target k, return the number of contiguous subarrays that sum to k.','SubarraySum','int',ARRAY['[]int','int']::text[],ARRAY['Use prefix sum and a map[prefixSum]count.','For each element, compute running sum. Check if sum-k exists in map; if so, add its count.','Update the map with the current sum.'],3,130,ARRAY['hashmap','prefix-sum','arrays','medium'],true,'MANUAL:subarray-sum-equals',$$Count subarrays whose sum equals k.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,1,1],2]'::jsonb,'2',false,1),('[[1,2,3],3]'::jsonb,'2',false,2),('[[1],0]'::jsonb,'0',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('majority-element','Hash Maps & Sets','function','go','Majority Element','Find the element that appears more than n/2 times in a slice. Assume the majority element always exists.','MajorityElement','int',ARRAY['[]int']::text[],ARRAY['Use Boyer-Moore voting algorithm: O(n) time, O(1) space.','Maintain a candidate and a count; cancel pairs of different elements.','The remaining candidate is the majority element.'],2,80,ARRAY['hashmap','voting','arrays','medium'],true,'MANUAL:majority-element',$$Find the element appearing more than n/2 times.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[3,2,3]]'::jsonb,'3',false,1),('[[2,2,1,1,1,2,2]]'::jsonb,'2',false,2),('[[1]]'::jsonb,'1',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('missing-number','Hash Maps & Sets','function','go','Missing Number','Given a slice of n distinct numbers from 0..n, return the one missing from the range.','MissingNumber','int',ARRAY['[]int']::text[],ARRAY['Compute expected sum = n*(n+1)/2.','Subtract actual sum from expected sum.','The difference is the missing number.'],1,50,ARRAY['hashmap','math','arrays','basic'],true,'MANUAL:missing-number',$$Find the missing number in a sequence.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[3,0,1]]'::jsonb,'2',false,1),('[[0,1]]'::jsonb,'2',false,2),('[[9,6,4,2,3,5,7,0,1]]'::jsonb,'8',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Concurrency
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('counter','Concurrency','function','go','Concurrent Counter','Increment a shared counter n times using goroutines. Return the final counter value. Use sync.Mutex for safety.','ConcurrentCounter','int',ARRAY['int']::text[],ARRAY['Use a sync.Mutex to protect the shared counter.','Launch n goroutines, each incrementing the counter by 1.','Use a sync.WaitGroup to wait for all goroutines to finish.'],3,140,ARRAY['goroutines','mutex','concurrency','medium'],true,'MANUAL:counter',$$Implement a concurrent counter with mutex.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[100]'::jsonb,'100',false,1),('[1000]'::jsonb,'1000',false,2),('[1]'::jsonb,'1',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('producer-consumer','Concurrency','function','go','Producer-Consumer','Implement a producer-consumer pattern. Given a buffer size, produce n items and consume them. Return the count of successfully consumed items.','ProducerConsumer','int',ARRAY['int','int']::text[],ARRAY['Use a buffered channel as the shared queue.','Producer sends numbers into the channel; consumer receives them.','Use a done channel or WaitGroup to signal completion.'],4,180,ARRAY['channels','goroutines','concurrency','hard'],true,'MANUAL:producer-consumer',$$Implement producer-consumer with channels.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[5,10]'::jsonb,'10',false,1),('[1,5]'::jsonb,'5',false,2),('[10,100]'::jsonb,'100',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('fan-in','Concurrency','function','go','Fan-In Merge','Merge multiple input channels into a single output channel using fan-in pattern. Return all values received from all channels in order.','FanIn','[]int',ARRAY['int','int']::text[],ARRAY['Launch a goroutine for each input channel that forwards to the output.','Use a WaitGroup to detect when all source channels are exhausted.','Close the merged channel after all sources are done.'],4,180,ARRAY['channels','goroutines','fan-in','hard'],true,'MANUAL:fan-in',$$Merge values from multiple channels into one.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[2,3]'::jsonb,'[0,1,2,0,1,2]',false,1),('[3,2]'::jsonb,'[0,1,0,1,0,1]',false,2),('[1,5]'::jsonb,'[0,1,2,3,4]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('worker-pool','Concurrency','function','go','Worker Pool','Given numJobs and numWorkers, dispatch jobs to workers and collect results. Each job i returns i*2. Return the sum of all results.','WorkerPool','int',ARRAY['int','int']::text[],ARRAY['Create a jobs channel and a results channel.','Start numWorkers goroutines that read from jobs and write to results.','Send numJobs to jobs, close it, then collect numJobs results.'],3,160,ARRAY['goroutines','channels','worker-pool','medium'],true,'MANUAL:worker-pool',$$Implement a worker pool pattern.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[5,2]'::jsonb,'20',false,1),('[10,3]'::jsonb,'90',false,2),('[1,5]'::jsonb,'0',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;
