-- =============================================================================
-- MODULE: Error Handling
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('divide','Error Handling','function','go','Divide with Error','Divide two integers and return the result as a float64. Return error if dividing by zero.','Divide','[]interface{}',ARRAY['int','int']::text[],ARRAY['Return []interface{}{result, error.Error()} or {0,""} on success.','If b is 0, return {0.0, "division by zero"}.','Use float64 for the division result (convert a and b first).'],2,70,ARRAY['errors','basic'],true,'MANUAL:divide',$$Divide two numbers, returning error on division by zero.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[10,2]'::jsonb,'[5.0,""]',false,1),('[7,3]'::jsonb,'[2.3333333333333335,""]',false,2),('[5,0]'::jsonb,'[0.0,"division by zero"]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('parse-int','Error Handling','function','go','Parse Integer with Error Handling','Parse a string into an integer. Return the integer or an error message if parsing fails.','ParseIntSafe','[]interface{}',ARRAY['string']::text[],ARRAY['Use strconv.Atoi to parse the string.','Return []interface{}{parsedValue, ""} on success.','On error, return {0, error message string}.'],1,60,ARRAY['errors','parsing','basic'],true,'MANUAL:parse-int',$$Parse a string to int with error handling.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["42"]'::jsonb,'[42,""]',false,1),('["abc"]'::jsonb,'[0,"strconv.Atoi: parsing \\"abc\\": invalid syntax"]',false,2),('["-5"]'::jsonb,'[-5,""]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('safe-slice-access','Error Handling','function','go','Safe Slice Access','Return the element at index i from a slice. Return an error if index is out of bounds.','SafeAccess','[]interface{}',ARRAY['[]int','int']::text[],ARRAY['Check if i < 0 or i >= len(slice).','Return {0, "index out of bounds"} on error.','Return {slice[i], ""} on success.'],1,50,ARRAY['errors','slices','basic'],true,'MANUAL:safe-slice-access',$$Safely access a slice element with bounds checking.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3],1]'::jsonb,'[2,""]',false,1),('[[1,2,3],5]'::jsonb,'[0,"index out of bounds"]',false,2),('[[],0]'::jsonb,'[0,"index out of bounds"]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('validate-email','Error Handling','function','go','Validate Email','Validate an email address. Return empty string if valid, or an error message describing the issue.','ValidateEmail','string',ARRAY['string']::text[],ARRAY['Check for exactly one @ symbol.','Ensure the local part (before @) is non-empty.','Ensure the domain (after @) contains at least one dot.'],2,80,ARRAY['errors','validation','strings','medium'],true,'MANUAL:validate-email',$$Validate an email address format.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["user@example.com"]'::jsonb,'""',false,1),('["invalid-email"]'::jsonb,'"missing @"',false,2),('["user@"]'::jsonb,'"missing domain"',false,3),('["@domain.com"]'::jsonb,'"missing local part"',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: File I/O
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('read-file-lines','File I/O','function','go','Read File Lines','Given a file path string and content string (simulated), return the number of lines in the content.','CountLines','int',ARRAY['string','string']::text[],ARRAY['Split content by newline character (\\n).','Count the resulting number of lines.','An empty string returns 1 (one line, empty).'],1,50,ARRAY['files','strings','basic'],true,'MANUAL:read-file-lines',$$Count lines in file content.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["dummy.txt","line1\nline2\nline3"]'::jsonb,'3',false,1),('["dummy.txt","hello"]'::jsonb,'1',false,2),('["dummy.txt",""]'::jsonb,'1',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('write-to-file','File I/O','function','go','Write To File','Given content, return a simulated write result. Write content to a file and return the number of bytes written. Simulate the file write operation.','WriteFileSim','[]interface{}',ARRAY['string','string']::text[],ARRAY['Return the length of content in bytes.','Use len(content) for byte count.','Return []interface{}{byteCount, ""} on success.'],1,50,ARRAY['files','strings','basic'],true,'MANUAL:write-to-file',$$Simulate writing content to a file and return byte count.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["test.txt","Hello, World!"]'::jsonb,'[13,""]',false,1),('["out.txt",""]'::jsonb,'[0,""]',false,2),('["data.txt","Go\nis\nawesome"]'::jsonb,'[13,""]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('csv-parser','File I/O','function','go','CSV Line Parser','Parse a single CSV line (comma-separated, values may be quoted with double quotes). Return the fields as a string slice.','CSVParse','[]string',ARRAY['string']::text[],ARRAY['Handle quoted fields with embedded commas.','A double-quote inside a quoted field is escaped as "".','Trim whitespace around unquoted fields.'],3,120,ARRAY['files','parsing','csv','medium'],true,'MANUAL:csv-parser',$$Parse a single CSV line into fields.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["a,b,c"]'::jsonb,'["a","b","c"]',false,1),('["\"hello, world\",foo,bar"]'::jsonb,'["hello, world","foo","bar"]',false,2),('["a"]'::jsonb,'["a"]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('file-extension-filter','File I/O','function','go','File Extension Filter','Given a list of filenames and a desired extension (e.g., ".go"), return only the filenames with that extension.','FilterByExt','[]string',ARRAY['[]string','string']::text[],ARRAY['Use strings.HasSuffix to check the extension.','Be case-sensitive (".Go" does not match ".go").','Return filenames in the order they appear.'],1,50,ARRAY['files','strings','basic'],true,'MANUAL:file-extension-filter',$$Filter filenames by extension.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[["main.go","main_test.go","main.go.bak"],".go"]'::jsonb,'["main.go","main_test.go"]',false,1),('[["a.txt","b.csv","c.txt"],".txt"]'::jsonb,'["a.txt","c.txt"]',false,2),('[[],"any"]'::jsonb,'[]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Networking
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('parse-url','Networking','function','go','Parse URL Components','Given a URL string, return its components as a map: scheme, host, path, query.','ParseURL','map[string]string',ARRAY['string']::text[],ARRAY['Use net/url.Parse to parse the URL.','Extract Scheme, Host, Path, and RawQuery fields.','Return nil if parsing fails.'],2,80,ARRAY['networking','url','parsing','medium'],true,'MANUAL:parse-url',$$Parse a URL into its components.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["https://example.com/path?q=hello"]'::jsonb,'{"scheme":"https","host":"example.com","path":"/path","query":"q=hello"}',false,1),('["http://localhost:8080/api"]'::jsonb,'{"scheme":"http","host":"localhost:8080","path":"/api","query":""}',false,2),('["invalid-url"]'::jsonb,'{}',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('ip-validation','Networking','function','go','IP Address Validation','Return true if a string is a valid IPv4 address (four octets 0-255 separated by dots).','IsValidIPv4','bool',ARRAY['string']::text[],ARRAY['Split the string by "."; expect exactly 4 parts.','Each part must be a non-empty numeric string 0-255.','Leading zeros are not allowed (e.g., "01" is invalid).'],2,80,ARRAY['networking','validation','ip','medium'],true,'MANUAL:ip-validation',$$Validate if a string is a valid IPv4 address.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["192.168.1.1"]'::jsonb,'true',false,1),('["256.1.2.3"]'::jsonb,'false',false,2),('["192.168.01.1"]'::jsonb,'false',true,3),('["abc"]'::jsonb,'false',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('build-query-string','Networking','function','go','Build Query String','Given a map of query parameters, build a URL query string (key=value&key2=value2). Sort keys alphabetically.','BuildQuery','string',ARRAY['map[string]string']::text[],ARRAY['Collect all keys and sort them.','Iterate sorted keys and append "key=value" separated by "&".','Use url.QueryEscape on values for proper encoding.'],2,90,ARRAY['networking','url','strings','medium'],true,'MANUAL:build-query-string',$$Build a URL query string from a parameter map.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[{"name":"John","age":"30"}]'::jsonb,'"age=30&name=John"',false,1),('[{"search":"go language","page":"1"}]'::jsonb,'"page=1&search=go+language"',false,2),('[{}]'::jsonb,'""',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('http-status-emoji','Networking','function','go','HTTP Status Emoji','Return an appropriate emoji for a given HTTP status code: 2xx=✅, 3xx=↪️, 4xx=❌, 5xx=💥, others=❓.','StatusEmoji','string',ARRAY['int']::text[],ARRAY['Check the hundreds digit of the status code.','Use integer division: code / 100.','Switch on the result (2, 3, 4, 5) for the emoji.'],1,40,ARRAY['networking','http','basic'],true,'MANUAL:http-status-emoji',$$Return emoji for HTTP status code category.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[200]'::jsonb,'"✅"',false,1),('[404]'::jsonb,'"❌"',false,2),('[500]'::jsonb,'"💥"',false,3),('[99]'::jsonb,'"❓"',true,4)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Interfaces & Generics
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('shaper','Interfaces & Generics','function','go','Interface: Shape Area','Define an Areaer interface and implement it for Circle (radius) and Rectangle (width,height). Return the area of the given shape.','ShapeArea','float64',ARRAY['string','float64','float64']::text[],ARRAY['Define interface Areaer with Area() float64.','Circle stores radius; Rectangle stores width,height.','Call the Area method and return the value.'],2,90,ARRAY['interfaces','oop','polymorphism','medium'],true,'MANUAL:shaper',$$Implement a Shape interface with area calculation.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["circle",5.0,0.0]'::jsonb,'78.53981633974483',false,1),('["rectangle",4.0,6.0]'::jsonb,'24.0',false,2),('["circle",0.0,0.0]'::jsonb,'0.0',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('min-generic','Interfaces & Generics','function','go','Generic Min Function','Write a generic function that returns the minimum value from a slice of ordered comparable types (int, float64, string).','MinGeneric','string',ARRAY['[]interface{}']::text[],ARRAY['Iterate through the slice comparing values.','Use type assertions or Go 1.18+ generics.','Return the min as a string representation.'],3,120,ARRAY['generics','comparison','medium'],true,'MANUAL:min-generic',$$Generic min function for comparable types.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[3,1,4,1,5,9,2,6]]'::jsonb,'"1"',false,1),('[[3.5,1.2,4.8,0.9]]'::jsonb,'"0.9"',false,2),('[["banana","apple","cherry"]]'::jsonb,'"apple"',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('stringer','Interfaces & Generics','function','go','Custom Stringer','Implement the Stringer interface for a Person struct (name, age). Return "Name: <name>, Age: <age>".','PersonString','string',ARRAY['string','int']::text[],ARRAY['Person has fields Name string and Age int.','Implement func (p Person) String() string.','Use fmt.Sprintf for formatted output.'],1,50,ARRAY['interfaces','stringer','basic'],true,'MANUAL:stringer',$$Implement String() method for a Person struct.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["Alice",30]'::jsonb,'"Name: Alice, Age: 30"',false,1),('["Bob",25]'::jsonb,'"Name: Bob, Age: 25"',false,2),('["",0]'::jsonb,'"Name: , Age: 0"',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('any-type-container','Interfaces & Generics','function','go','Any-Type Container','Create a generic container that holds a slice of values of any type. Implement Add, Get, and Len methods. Return results as JSON-like string.','AnyContainer','string',ARRAY['[]interface{}']::text[],ARRAY['Define a generic type Container[T any] struct with Items []T.','Add method appends, Get(i int) returns element at i, Len returns length.','Return the Items as a string representation.'],3,110,ARRAY['generics','containers','medium'],true,'MANUAL:any-type-container',$$Generic container with Add/Get/Len methods.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[10,20,30]]'::jsonb,'"[10,20,30]"',false,1),('[["x","y"]]'::jsonb,'"[x,y]"',false,2),('[[]]'::jsonb,'"[]"',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: Pointers
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('swap-pointers','Pointers','function','go','Swap Using Pointers','Swap two integers using pointers (modify the original values). Return []int{a,b} after swap.','SwapPointers','[]int',ARRAY['[]int']::text[],ARRAY['The input is a slice [a,b]. Create pointers to each.','Swap the values through dereferencing: *a, *b = *b, *a.','Return the slice with original references now swapped.'],1,50,ARRAY['pointers','basic'],true,'MANUAL:swap-pointers',$$Swap two integers using pointers.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[5,10]]'::jsonb,'[10,5]',false,1),('[[-3,7]]'::jsonb,'[7,-3]',false,2),('[[0,0]]'::jsonb,'[0,0]',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('double-ptr','Pointers','function','go','Double via Pointer','Given an integer pointer, double the value it points to and return the new value.','DoublePtr','int',ARRAY['*int']::text[],ARRAY['Dereference the pointer with *ptr.','Double the value and assign back: *ptr = *ptr * 2.','Return the new value.'],1,40,ARRAY['pointers','basic'],true,'MANUAL:double-ptr',$$Double a value through a pointer.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[5]'::jsonb,'10',false,1),('[0]'::jsonb,'0',false,2),('[-3]'::jsonb,'-6',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('linked-list-get','Pointers','function','go','Linked List Get','Given a slice of values and a target index, build a singly-linked list and return the value at the given index. Return -1 if index out of bounds.','LinkedListGet','int',ARRAY['[]int','int']::text[],ARRAY['Define struct Node {Val int; Next *Node}.','Build the list by linking nodes iteratively.','Traverse the list to the given index (0-based).'],2,90,ARRAY['pointers','linked-list','medium'],true,'MANUAL:linked-list-get',$$Get value at index from a linked list built from a slice.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[[1,2,3],1]'::jsonb,'2',false,1),('[[10,20,30],0]'::jsonb,'10',false,2),('[[1],5]'::jsonb,'-1',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('make-ptr-nil-safe','Pointers','function','go','Nil-Safe Pointer','Given a pointer to an integer, return its value if non-nil, or -1 if nil.','NilSafeDeref','int',ARRAY['interface{}']::text[],ARRAY['Check if the pointer is nil before dereferencing.','Use type assertion or reflection to handle *int.','Return -1 if nil, else return the pointed value.'],2,70,ARRAY['pointers','nil-safety','medium'],true,'MANUAL:make-ptr-nil-safe',$$Safely dereference a pointer that may be nil.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[42]'::jsonb,'42',false,1),('[null]'::jsonb,'-1',false,2),('[-1]'::jsonb,'-1',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

-- =============================================================================
-- MODULE: OOP & Composition
-- =============================================================================

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('bank-account','OOP & Composition','function','go','Bank Account','Design a BankAccount struct with deposit and withdraw methods. Return account summary after operations.','BankAccount','map[string]int',ARRAY['[]string']::text[],ARRAY['Account has Owner string and Balance int.','Deposit(n int) adds to balance. Withdraw(n int) subtracts if sufficient funds.','Return map with "owner" and "balance" keys.'],2,80,ARRAY['oop','structs','methods','medium'],true,'MANUAL:bank-account',$$Design a bank account with deposit/withdraw.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[["Alice:deposit:100","withdraw:30"]]'::jsonb,'{"owner":"Alice","balance":70}',false,1),('[["Bob:deposit:50","withdraw:100"]]'::jsonb,'{"owner":"Bob","balance":50}',false,2),('[["Charlie:deposit:200"]]'::jsonb,'{"owner":"Charlie","balance":200}',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('composition-vs-inheritance','OOP & Composition','function','go','Composition: Vehicle','Demonstrate Go composition: embed Engine in Car and Bike. Return "vroom" if the vehicle has an engine, "silent" otherwise.','VehicleSound','string',ARRAY['string']::text[],ARRAY['Define Engine struct with Sound() string.','Embed Engine in Car and Bike structs.','Call Sound on the embedded Engine.'],2,80,ARRAY['oop','composition','structs','medium'],true,'MANUAL:composition-vs-inheritance',$$Demonstrate Go composition via embedded structs.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["car"]'::jsonb,'"vroom"',false,1),('["bike"]'::jsonb,'"vroom"',false,2),('["tricycle"]'::jsonb,'"silent"',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('method-receiver-value-vs-pointer','OOP & Composition','function','go','Method Receiver Types','Demonstrate the difference between value and pointer receivers. Given initial value, apply methods and return final value.','ReceiverDemo','int',ARRAY['int']::text[],ARRAY['Create Counter struct with Value int.','AddValue(takes value receiver, returns copy). AddPtr(takes pointer receiver, modifies original).','Return the final value after operations.'],2,80,ARRAY['oop','methods','receivers','medium'],true,'MANUAL:method-receiver-value-vs-pointer',$$Demonstrate value vs pointer method receivers.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('[5]'::jsonb,'10',false,1),('[0]'::jsonb,'0',false,2),('[-3]'::jsonb,'3',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;

WITH p AS (INSERT INTO problems (slug,module,type,language,title,statement,func_name,return_type,param_types,hints,difficulty,xp_reward,tags,visible,source_hash,raw_readme) VALUES ('constructor-pattern','OOP & Composition','function','go','Constructor Pattern','Design a Config struct with fields Host, Port, Timeout. Implement a NewConfig function with defaults: localhost, 8080, 30.','NewConfig','map[string]interface{}',ARRAY['string','int','int']::text[],ARRAY['Define Config struct with Host, Port, Timeout.','If host is empty, default to "localhost". If port is 0, default to 8080. If timeout is 0, default to 30.','Return map with config fields.'],1,60,ARRAY['oop','constructor','structs','basic'],true,'MANUAL:constructor-pattern',$$Design a Config struct with constructor and defaults.$$) ON CONFLICT (slug) DO NOTHING RETURNING id)
INSERT INTO test_cases (problem_id,input,expected,is_hidden,ordinal) SELECT id,input,expected,is_hidden,ordinal FROM p,(VALUES ('["",0,0]'::jsonb,'{"host":"localhost","port":8080,"timeout":30}',false,1),('["example.com",9090,60]'::jsonb,'{"host":"example.com","port":9090,"timeout":60}',false,2),('["test",0,10]'::jsonb,'{"host":"test","port":8080,"timeout":10}',true,3)) AS t(input,expected,is_hidden,ordinal) WHERE id IS NOT NULL;
