import re
import os

files_to_update = [
    'migrations/004_problem_seeds.sql',
    'scripts/seed_all_modules.sql',
    'scripts/seed_all_modules_part4.sql'
]

updates = {
    'reverse-string': r'Given an input string, return a new string with the characters in reverse order.\n\n**Details**\nIn Go, strings are UTF-8 encoded and immutable. This means you cannot simply reverse the bytes of a string without potentially breaking multi-byte characters (runes). You must carefully iterate over the string as a sequence of runes, build the reversed sequence, and construct a new string from the result.\n\n**Considerations**\n- An empty string should return an empty string.\n- A single-character string should return itself.\n- Ensure that multi-byte characters (such as emojis or accented letters) are not split or corrupted during the reversal process.\n\n**Solve Time Estimate**\n~15 minutes',
    'is-prime': r'Determine whether a given positive integer is a prime number. Return `true` if it is prime, and `false` otherwise.\n\n**Details**\nA prime number is a natural number greater than $1$ that has no positive divisors other than $1$ and itself. The first few prime numbers are $2, 3, 5, 7, 11, 13, 17, 19, 23, 29$.\nYour implementation should efficiently check for primality. A naive approach iterates up to $n-1$, but an optimal approach only requires checking up to $\\lfloor\\sqrt{n}\\rfloor$.\n\n**Considerations**\n- $1$ is not a prime number.\n- $2$ is the only even prime number; all other even numbers greater than $2$ are composite.\n- Consider edge cases where $n$ is very small.\n\n**Solve Time Estimate**\n~15 minutes',
    'sum-even-numbers': r'Calculate the sum of all even integers within a provided slice. Return $0$ if the slice is empty or contains no even numbers.\n\n**Details**\nThis problem requires you to iterate over a collection of integers, filter out the odd numbers, and accumulate the sum of the even ones. An integer $n$ is even if $n \\pmod 2 = 0$.\n\n**Considerations**\n- The input slice may contain negative numbers. Ensure your parity check handles negative values correctly (e.g., $-4 \\pmod 2 = 0$).\n- An empty slice should gracefully yield a sum of $0$.\n\n**Solve Time Estimate**\n~15 minutes',
    'merge-sorted-arrays': r'Given two sorted integer slices, merge them into a single sorted slice containing all elements from both inputs in ascending order.\n\n**Details**\nSince both input arrays are already sorted, you can achieve an optimal $O(N+M)$ time complexity using a two-pointer approach. Maintain a pointer for each slice, compare the current elements, and append the smaller one to your result slice.\n\n**Considerations**\n- Either or both of the input arrays might be empty.\n- The arrays may contain duplicate values.\n- Do not use built-in sorting functions (e.g., `sort.Ints()`); leverage the pre-sorted nature of the inputs to build the merged array efficiently.\n\n**Solve Time Estimate**\n~25 minutes',
    'word-frequency': r'Count the frequency of each word in a given sentence and return the result as a map.\n\n**Details**\nText processing is a fundamental skill. For this task, you must:\n1. Split the sentence into individual words using spaces as delimiters.\n2. Normalize all words to lowercase so that "Hello" and "hello" are treated equally.\n3. Remove any leading or trailing punctuation from each word.\n4. Tally the occurrences of each normalized word in a map.\n\n**Considerations**\n- Empty tokens resulting from consecutive spaces should be ignored.\n- Punctuation to strip typically includes characters like `.`, `,`, `!`, `?`.\n\n**Solve Time Estimate**\n~30 minutes',
    'matrix-diagonal-sum': r'Given a square integer matrix (a 2D slice of size $n \\times n$), calculate the sum of the elements located on the main diagonal.\n\n**Details**\nThe main diagonal of a matrix consists of the elements extending from the top-left corner to the bottom-right corner. Mathematically, these are the elements where the row index equals the column index (i.e., `matrix[i][i]`).\n\n**Considerations**\n- The matrix is guaranteed to be square ($n \\times n$).\n- Avoid nested loops; you only need to iterate over the dimension $n$ once.\n- A $1 \\times 1$ matrix should simply return its only element.\n\n**Solve Time Estimate**\n~20 minutes',
    'rotate-matrix': r'Rotate a given $n \\times n$ square matrix by 90 degrees in a clockwise direction. Return the newly rotated matrix without modifying the original input.\n\n**Details**\nMatrix rotation is commonly used in image processing algorithms. A 90-degree clockwise rotation maps the element at `matrix[i][j]` to `rotated[j][n-1-i]`.\n\nAlternatively, a matrix can be rotated clockwise by first transposing it (swapping rows and columns) and then reversing the elements of each row.\n\n**Considerations**\n- Allocate a new 2D slice for the result; do not mutate the input array (out-of-place rotation).\n- The matrix is guaranteed to be a square.\n\n**Solve Time Estimate**\n~35 minutes',
    'balanced-parentheses': r'Determine if a string contains correctly matched and nested parentheses and brackets. Supported pairs are `()`, `[]`, and `{}`.\n\n**Details**\nYou must verify that every opening bracket has a corresponding closing bracket of the exact same type, and that they are closed in the correct order.\nThis problem is best solved using a Stack data structure. As you iterate through the string, push opening brackets onto the stack. When you encounter a closing bracket, check if it matches the bracket at the top of the stack.\n\n**Considerations**\n- Ignore any characters that are not parentheses or brackets.\n- The string is considered unbalanced if you encounter a closing bracket when the stack is empty, or if the stack is not empty after processing the entire string.\n- An empty string (or a string with no brackets) is considered balanced.\n\n**Solve Time Estimate**\n~30 minutes',
    'longest-common-prefix': r'Find the longest common prefix string shared among an array of strings. If there is no common prefix, return an empty string.\n\n**Details**\nA common prefix is a substring at the very beginning of a string that appears identically across all strings in a dataset.\nYou can solve this by comparing characters column by column across all strings, stopping at the first column where a mismatch occurs or when you reach the end of the shortest string.\n\n**Considerations**\n- If the input array is empty, return `""`.\n- If the array contains only one string, that string itself is the longest common prefix.\n\n**Solve Time Estimate**\n~25 minutes',
    'two-sum-indices': r'Given a slice of integers and a target integer, return the indices of the two numbers that add up to the target.\n\n**Details**\nYou may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.\nWhile a brute-force $O(N^2)$ solution checks every pair, an optimal $O(N)$ solution uses a Hash Map to store the indices of the numbers you have seen so far, allowing you to check if the complement (`target - current_number`) exists in constant time.\n\n**Considerations**\n- The input slice may contain negative numbers.\n- Exactly one valid pair is guaranteed to exist.\n\n**Solve Time Estimate**\n~35 minutes',
    'edit-distance': r'Given two strings `word1` and `word2`, return the minimum number of operations required to convert `word1` to `word2`.\n\n**Details**\nThis is a classic problem in computer science, known as the Levenshtein distance. You are permitted three operations on a string:\n1. Insert a character\n2. Delete a character\n3. Replace a character\n\nThis problem exhibits optimal substructure and overlapping subproblems, making it a perfect candidate for Dynamic Programming.\nLet `DP[i][j]` represent the minimum edit distance between the first `i` characters of `word1` and the first `j` characters of `word2`.\n- If the characters match (`word1[i-1] == word2[j-1]`), no operation is needed, so `DP[i][j] = DP[i-1][j-1]`.\n- Otherwise, you must perform an operation, leading to `DP[i][j] = 1 + min(insert, delete, replace)`.\n\n**Considerations**\n- Base cases: When one string is empty, the edit distance is the length of the other string (all insertions).\n- Be mindful of string indexing versus DP table indexing (which usually is 1-based to handle empty prefixes).\n\n**Solve Time Estimate**\n~45 minutes'
}

for filepath in files_to_update:
    if not os.path.exists(filepath):
        continue
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for slug, new_stmt in updates.items():
        # Match the exact statement inside the VALUES for that slug.
        # This requires matching the pattern:
        # VALUES (\n        'slug', ... 'statement',
        # But wait, it's easier to find the exact statement string if we use regex.
        # However, SQL files have standard patterns.
        # In 004_problem_seeds:
        # 'reverse-string',
        # 'piscine',
        # 'function',
        # 'go',
        # 'Reverse String',
        # 'Given a string, return a new string with the characters in reverse order.',
        #
        # In seed_all_modules.sql:
        # VALUES ('slug','module','type','language','title','old_statement',
        pass
        # I'll just use regex replacement carefully.
