export const MONACO_EDITOR_OPTIONS = {
  minimap: { enabled: false },
  fontSize: 14,
  fontWeight: "500",
  fontFamily: "var(--font-mono), monospace",
  padding: { top: 16, bottom: 16 },
  renderLineHighlight: "all",
  cursorBlinking: "smooth",
  cursorSmoothCaretAnimation: "on",
  smoothScrolling: true,
  scrollbar: {
    verticalScrollbarSize: 8,
    horizontalScrollbarSize: 8,
    alwaysConsumeMouseWheel: false,
  },
  overviewRulerLanes: 3,
  hideCursorInOverviewRuler: false,
  bracketPairColorization: { enabled: true },
  matchBrackets: "always",
  autoClosingBrackets: "always",
  autoClosingQuotes: "always",
  autoIndent: "full",
  formatOnPaste: true,
  tabSize: 4,
  insertSpaces: true,
  quickSuggestions: {
    other: true,
    comments: false,
    strings: false,
  },
  snippetSuggestions: "inline",
  suggestOnTriggerCharacters: true,
  acceptSuggestionOnEnter: "smart",
  suggestSelection: "first",
  wordWrap: "off",
  folding: true,
  foldingHighlight: true,
  foldingStrategy: "indentation",
} as const;
